site_name: CivicTechWR Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Policies:
    - Code of Conduct: policies/Code_of_Conduct.md
    - Diversity and Inclusion Policy: policies/Diversity_and_Inclusion_Policy.md
  - Guidelines:
    - Communication Guidelines: guidelines/Communication_Guidelines.md
    - Contribution Guidelines: guidelines/Contribution_Guidelines.md
    - Event Planning Guide: guidelines/Event_Planning_Guide.md
    - Social Media Guidelines: guidelines/SocialMedia_Guidelines.md
  - Meeting Minutes:
    - Overview: meeting-minutes/index.md
    - 2024-06-19 Meeting Minutes: meeting-minutes/2024-06-19_Meeting_Minutes.md
  - Templates:
    - Event Planning Template: ctwr-templates/Event_Planning_Template.md
    - Meeting Minutes Template: ctwr-templates/Meeting_Minutes_Template.md
  - FAQ: faq/index.md
  - Get Involved:
    - Meetup: 'https://www.meetup.com/civictechwr/'
    - Slack: 'https://join.slack.com/t/civictechwr/shared_invite/zt-2ldijjy0i-gaGvPkuafPt9Zpn7jml70w'
    - GitHub: 'https://github.com/CivicTechWR'